def extract_calibration_value(line):
    digits = [char for char in line if char.isdigit()]
    if not digits:
        return 0
    first_digit = digits[0]
    last_digit = digits[-1]
    return int(first_digit + last_digit)

def sum_calibration_values(document):
    lines = document.split('\n')
    total = 0
    for line in lines:
        total += extract_calibration_value(line)
    return total

# Exemple de document
document = """ckmb52fldxkseven3fkjgcbzmnr7
gckhqpb6twoqnjxqplthree2fourkspnsnzxlz1
2onetwocrgbqm7
frkh2nineqmqxrvdsevenfive
four9two
six7sixqrdfive3twonehsk
xkvsone2
one65
rggxsff1seven
djbcgrrtqdshpqqzj43rgcr
br89fivetwoqggnxjfourtl3
zoneight47five5sixjxd74
4five1
5seveneighteightzzbnzsvdjnkvndsxlttfour
htdcmsl12ninethreepkqtdlvtl
twocghtvtdlfchfqnjhrfour19
rptwofiveonecvlldmppxtrvj3
6gqsvsqpzxj
5twomgkzsvg
4ninedflntfsn1
4threethree
43two6eight9
4gqnkntjthree9one45
9lmjgqnkxqvfrzhbcfrlltjxjlkjfrlmb3
ninethreejkcbplfg4kseventwo
mbkfgktwolbvsptgsixseven1oneightzvm
m5fvqfkkk
tptqnsxmsevencrkdmxms55zrfmpmzv7lzqlnmbkzt
bqccqhbdgeight7
four7nine1eight
8fivethndnpztzninepdkfive8
1sixxvqdfourlnpdrfbnnx41vhqgth
sgpkgdb9
fivetwoq7cdprnjdjhs3three9
1mfvptbhqshblvvvdl
ztftqgbzld8jkcmsrdfzonemzdmbzxpfour
dfkctqcjbmfourhszmlvtkeightthree2
4onersrfjcskckcxcj4sevenzzzpsixeight
1fourr5gxpone
seven74ninersgvvmtgsix
jvtwonefivetwosbpglbx2two
fourfivecxgssssixtwofour4
3zcgcjdcpbgqdfnhxtneight
fourfour29cpbccthree44
6six9foureight5xmfdf
four77
tqtnjshdmtwo3four8one27
one52
nine32five3six
qcjbjrpqdtpvveightpmzs17fourjvghvl
5293gmtdttfpmrlhvlt9
2zonenfglkskxhn3gxbrtxtcpfive
three5cfourfvmqlnhp4two
three4knrdzxpr
fmpvqkxgeightthreebdrng9tdcffvsfctwo
jpktgx8fivegqeight5three
7sevennine
3two3
nfthhzcq2
plmbtrzbnbmt1nine
149hvjbktkmbj8mtnrblcvfive7seven
bfthree1
six6kqprz86two6
jthree6
nine2hzrlcqrt7eight
nnzhkhpdb8rbnqmxrfive
rkszqnp1
t1
5sixlmxkgmxrgveight3
sevenlptpdhtjpgxconedvtrrnngn8
nlpvxbscttbbpgndnc7jvrtcjxbsxnqvfcxdcfrgtrdkjflzlrqcnmfourkznnmrv
7kllgxpb6
two4eightfgrsix1five7six
one2three6hmktjgmbxhbjl
bqjtxhntjreightsevendgcfpmkld14four
22pgcslxtdhkhz8ninethreethreejcklznxq
146gqthree85twoseven
vlvxlmkfpcxsstsevencdbbdsix6
5sixseven48
llljbtxtrrpssrfthree9dpvrndphhn
qkhvq5
svrfthree8bdhjshcftdnine4
nfqnfkpchl5pcstz
pbx5mfkfour8
cptwonethreeptwo9gzmlkv9
gdpkprlzr6466fxlvfour
dlnpklqtfivesixfptrdh9four
onedpfskdd38qfvbjdnpglone
4sevenseven5qf
onepgmmhlgmtvone3c
247tsnmkd
threeznnnbtfive5tmdfxtwothree3ndjcszrb
oneeight6rhfiveone
threethreethreestvgljm4seven
bfbrk3vqsmone39hzzxdgp6eight
98rndphxhcbl
57fourlntgdngzpdsjkbbxnv7
twons4
three4threesixtwo2hf
lgqtcllzsevenhrrhqsmsnncmlz7
8fnngjrxtljncbvlt7ninehfzrthree
12mltqtqqrvjmjsbthnzpdjtwo1
lf1onevdmn2
3twozlqnddmrsixslphpvb
five4nrtcjmvj
cksgmkszrbsrgfkq7tqjxsshxxh7vngsnjt
mfiveone7
kkvtwone5sevenfcfnngpmjktrpxk7djgzmdthreehpp
fxbgtcjp4pxpjv5rbfllhfcpfive8
2gxrkjdtvxmnvs76
npvvleightlpd354vrfh1
zbnzdlzpqzsixnine4sevenqtddzzm6
6cxrhdvzbmthree98
77eightnine32four
56tshj77one
161xk26mspxkchfourfive
onenineljnsmvmfb7
6hxvmqtwo
khzninetwo3pbtsqxlqj3
1nine3
6xrzjskblfq
kbtsbckkonethreetwofour7lgcbxmjkjpnine
fivethreecrjznine7
8qxjdsspgn
vdoneightsix7h9
5bsjl
gfllsrrrmzbfqdrlnvtdzr3
7hs2
1onelseventwo
fivetwo3
2gnxv9sevenseven
gmmhshzvsixzssixseven6fivehbdvsjdz
75onegckzsnpnine1xfslhfour6
sixgjhnfvsjnrsixeightnine49
nineseven929rlsdkcpbjrjdlptjbzp2
9hbpplffngltfourpgk
twoldknnqxkkvvdjldqthree373
cceight9two
zmeightwohkgs6
6sevenfdmqkss4fivethreesevenfourqfnsvvsj
4two9njeightnine
two3gzseveneightfour88eight
2clqj
1ndvbhbtql
five4sixseven5ghlgbmdgfnqpfdm
34dt
9sevenrl5
dpbpqppsixngvmkflllcrtn8
sixgvsctkrp53sbsx
nine9qdrqfourjc
zvppfjpqch24
sg4txzzfoursevenninethreesqcdznksix
one3six2
5bgdjzxbrlsl3sixlbxtjdpgfkjmq2
drsldhgjtrvmmz3jgrp6
qkeightwosix95nine445cfnine
fivetwo82scjct7onegblrqrggv9
threepfgljkghzc9
8qvzljppstpnpeight9
8nine98tkxcfqtg
sevensix4two
2eightthree
cvhhmcgknj6threefive87
seveneight7dsvqnjsjsqlkeightwovzt
71oneseven9fiveeightnh
pdjtzxbgjxb3vzfdnjbthree
xqpfourmpddnfcc4one5
jnrms1fkssgpvvlrmf
jbnkeightone6zldns85sixnine
1fourbqfgxscdxmkvdpsrm
eightsixone8mjbrqkplkqntjdlfourpjdcs
lxdsp6prmfglvdfz9eight7sevensixone
qdksixvmsevent7xlvmtzdkhb
8spqjvhplpzldpthree2
zqfvpq7pz22
nnfbpfour1
one9ninetwovrclctwo
344six98seven
kqkj9qqvfxn
seven1fivethree
shlnhgq2c3oneseveneightwodv
eightthreepkcxlk7threeonethreetwo
pgmbhrzzqmvkjl57fourqk8gxjmbfqcjs9
eight5oneights
ninenineeightvkrsrkgh8
svnfdxxftkgzpjqxzkmbbcfourvfsg3two6twonezqn
mnvqcmkqvjlqvtltgdpktr3dkgkbt
sixmg29pplfzrsqhlvfeight
glzsbmzqjj43
1zqrnpqrcbzdsnfour67zpsxpkbbkmfgrzm
kxbbcjjksix7sixeightnine
zbnhsdxgt5sixsixeightlsdqrgseven
ninezxrllznbcvmldxfbvjx5fivedtpdhsjgk8
reightwo7
fiveninenftgfourjbdkxtxcb38two
sixlpck4sixzcppvhzkchmnpvqjjgffourj
34pmfdthreetwo
7zbnnkqone5three
qxkmhcllcqkk5qrqseven47
one62brghc8s
twotwo1xvgcxbthree
three83dfqgjlc8eight
twofive8l1twocqmcccgdm
two6cnine
h2sfnczjmslpmlvdlzrs
9nbblsvxbhdxqfour8
kfzcsg6sixonevrbchsjtfivenbz
mgtlqcdtwo7qxmszcqpjdplccxzccsixone5nine
mtfpphckdn1eightpdtkssqlxdhtlmcjxb
jbphmjjjrg2159eight
zqskrzb1pgfouronevxscgtlccl
lxvpgrck8fxhxm
fournrnlfive1xt
3nsjnb
eight1three513nine
39eightsevenfourbgd1mbljzone
6two88five2pjpp
fourjlftf7six1xsktfhcdff
3kcntzlmnnhhmtmlftggqljkrvninetwo
threesixonexlvxrblq24
xpgzzrcckdlnrczxndplbpcb452
ninembdnhhnhhzmvmtdjtkzmb9ncq9one
4fivebrqrxftwo
84tqzbcvgdrgpzpxjrone83zgzpsix
99five
mgsevenqgkckfhbfnine3
2seventhree
8fivethreefive2fivethreefive
scrtqsevenjmxlvjrrbdtqgrdghfivethree7seven
sevensix946onesevenfour
dzn14
nineqbxvponekvfffs96zjfhpthree
53twoqknxnxqbcone
fhonerone7fourpmxskkmmx7
eightlq4fourfourdbsdrvhhs17
nnpgtgcbvrggctbtkzht5xmkhtnnn7brpxjcxdrone
threecxnqkmrrpmzdljstdbfmk5seven
sdptbzqhn7sixnine8
five7jdzdzfqfivesevengtznjmqrblkkzkgvt
fclvllfthx47sixbhq16
9mbmsxbn
three82fiveseven4
p1kzmzpbhmcthree
eightj3681nmgt8
2two7
jdbjlvxhhzzsnmcqldrldeight6nine4
2threefive
foursevenrmfhjvzdv8bpbrvblll1onetwofive
65cfgkcrhbjk
6onecjxzxb72gmrblthx
4jlrvckc9
doneightghmjzzrfourfdzxflm51nineseven7xkxt
r5eightone
nkgknm1
rxbsnnzbrs4two4
1pqvmfh
r2vpdpkzqcs85
gtfzjnnhsknvjnmnine98
zrdgv4hnbpb
7one165vddbrzpmfhskvzxdh3
44szfpgjmvgt4eight
dbgttrbj6five85nsqmzscksvdxks
ffkrhbvq2
6fourbpjrdvlk
38eightsix
two4fivedzpgfbtm
3jbk46
slpkmrstrrvthreepl9bhctdfnfzc
nine4two5kkfmcjgxbqkttg
1zppnmcr5sjfsbbxh48one
8one8fourseven5
6three7nineeight6
96three
91twonelt
5sevenone2sixthreeknhzm
2fvhgcbvg7sevenzqdtftct7tvvtkpxbrq8
9nvr
eightfivetwodjg9
7four2six
5fkzgffzpgp3
75sevenfive
mxtwonexsdrpkqzgm1threejqftvl
onekxffhsqb4dkb9fivefvtcjsd
eightone1eighteight4
glfeight7eight4
eightcdfjjfiveeight4fivetwo
npxnp32kfsfjpggdtpkm5
seven7threevcb
xtcvsmdx2four2twonefl
mzkgnzstwo844dcseight
zgoneight65z1seven3
1two5lc
threevsrg5vdmfvpss27qzrmvmbz
7qbcnjg1nine1seven3seven
5fourxdxrhmxsj
v78
41nine
56fmktkxvltp4bztxkqfrdthreefive4
fourdnq1
ctlk31srscmmdn66sevendmjjqvgj
b7nine8ninejqqhhdnnpx5
ninedlxdshrzfmrnnq17
jbneightwofiversjctwogvvtprslpgfour9xcone
dpt5hbgbnmdlthree5sixvsvqtnmndpvv
seven691rjmnfzddfive
466mmgnh
dsctthree7
eightqlfourzndmzltp34xjbdmpjs1
stmprbctwo1ninesxbzqkkdqgdqhone
sevensixeight91sixjscqxlzj4
vrctfpbp2bdknhtwothree68ckzlgkghponeightg
one82lzh1m9
5dgkljnlvnthbdfeight7xqqtgdoneightdvm
threeeight3t
5fourlpqzq2two1oneqlq
eightfivesixnineeightfour1
52ppqztdggqgtphdfz4fkrkfztzzqldpg
seven7zbone
xg79onef6eighteight
three6nvhnqeightgkttsvtwofive9
rjsevenonefllcrdnbmqcmxqsq38
twoseven2dppxgmlhr61onenine4
sevenb3btzhscqbrxxjkhtzpv
859two
threetllmjmhdjr18two
94tmvfpzmgvzsm1fmbhkhzffkzllx
nlkndffq2three
6ninemfour8rbxvj6
7clxtxrt1lqg5
onefivegjnfzkvg9
fplrvmqjdfxvjdfivesix6rpnkfour
5fivetwoxdgchbjjrckntlgblsxlcznfd
eight7fourfour
3kmtjlfbgssixmspkfzrgxtctksix4onetwones
8five15sixthreeljsfive
9lnn
nine7pzrxnnkthreesdjxphsrf4hc8
three6115nqhllcmpmzcfour
vpqjnvmltx8fivefive
vrlqlj5fivesixninebqhgcpgmgkmflvn
76eighteight7
8qkmnsjxbfhcpsvn4
oneninexqdseven4threefive
rpcvmnng162fivesixseven
31628eightthree
83d6fsfqdghztwo7bmvrlh
gknfcdqlrs25
9gkkth2ps
bxnvsjxqleight9ninenine
rsmcrqlnhsmjhspseven96vsckknrggbjd4tgtgbkxgvt
8seveneightcxrh
tkmfour8fivevl9one
8mgrxk
fourbgckqkeight6f
threetwo3eight652pp
ninefivetwojbhglxfxzfctwo8
jmjtcvpsxzdbkbqthree1qmgznpbzlthree4six1
foursix5
6nbdzdlmqpdlgpcclc
24
pseven3threeeightseven
7nine7gjdksbtqrrdsr
5ppflb48tkcffone8six
five2two7hstbbqzrninegbtwo2
eightfblzpmhs4
fbbdeightzzsdffh8jbjzxkclj
3nine6five1"""

# Calcul de la somme
total_sum = sum_calibration_values(document)
print(total_sum)  # Output: la somme des valeurs d'étalonnage